#pragma once

#include "Reader.h"

enum Opcode
{
	TURN_ON, TURN_OFF, WRITE_PIN, READ_PIN,
	READ_GLOBAL, WRITE_GLOBAL,
	SCRIPT_CALL,
	SCRIPT_START, SCRIPT_STOP,
	SCRIPT_PAUSE, SCRIPT_RESUME,
	JMP, JZ, JNZ, JNE, JLT, JLTE, JGT, JGTE,
	READ_LOCAL, WRITE_LOCAL,

	PRIM_READ_PIN, PRIM_WRITE_PIN, PRIM_TOGGLE_PIN,
	PRIM_SERVO_WRITE, PRIM_SET_SERVO_DEGREES, PRIM_GET_SERVO_DEGREES,
	PRIM_MULTIPLY, PRIM_ADD, PRIM_DIVIDE, PRIM_SUBTRACT,
	PRIM_SECONDS, PRIM_MILLIS, PRIM_MINUTES,
	PRIM_EQ, PRIM_NEQ, PRIM_GT, PRIM_GTEQ, PRIM_LT, PRIM_LTEQ,
	PRIM_NEGATE,
	PRIM_SIN, PRIM_COS, PRIM_TAN,
	PRIM_TURN_ON, PRIM_TURN_OFF,
	PRIM_YIELD, PRIM_DELAY_MILLIS,
	PRIM_DELAY_SECONDS, PRIM_DELAY_MINUTES,
	PRIM_RET, PRIM_POP, PRIM_RETV,
	PRIM_COROUTINE,
	PRIM_LOGICAL_AND, PRIM_LOGICAL_OR,
	PRIM_BITWISE_AND, PRIM_BITWISE_OR,
	PRIM_SERIAL_WRITE,
	PRIM_ROUND, PRIM_CEIL, PRIM_FLOOR,
	PRIM_SQRT, PRIM_ABS,
	PRIM_LN, PRIM_LOG10, PRIM_EXP, PRIM_POW10,
	PRIM_ASIN, PRIM_ACOS, PRIM_ATAN, PRIM_ATAN2,
	PRIM_POWER,
	PRIM_IS_ON, PRIM_IS_OFF,
	PRIM_REMAINDER, PRIM_CONSTRAIN,
	PRIM_RANDOM_INT, PRIM_RANDOM,
	PRIM_IS_EVEN, PRIM_IS_ODD,
	PRIM_IS_PRIME, PRIM_IS_WHOLE,
	PRIM_IS_POSITIVE, PRIM_IS_NEGATIVE,
	PRIM_IS_DIVISIBLE_BY, PRIM_IS_CLOSE_TO,
	PRIM_SONAR_DIST_CM,
	PRIM_MATRIX_8x8_DISPLAY,
	PRIM_MOD,
	PRIM_TONE, PRIM_NO_TONE,
	PRIM_GET_PIN_MODE, PRIM_SET_PIN_MODE,

	PRIM_LCD_INIT0, PRIM_LCD_INIT1, PRIM_LCD_PRINT_VALUE,
	PRIM_ARRAY_INIT, PRIM_ARRAY_GET, PRIM_ARRAY_SET, PRIM_ARRAY_CLEAR,
	PRIM_ARRAY_SUM, PRIM_ARRAY_AVG, PRIM_ARRAY_MAX, PRIM_ARRAY_MIN,
};

struct Instruction
{	
	uint8 opcode; // INFO(Richo): Originally an Opcode, but changed to uint8 to save 1 byte.
	uint8 data; // INFO(Richo): The msb is used as a breakpoint flag, the argument is stored as a 7-bit signed int
};

void readInstruction(Reader* rs, Instruction* instruction, bool& timeout);

void setBreakpoint(Instruction* instruction, bool value);
bool getBreakpoint(Instruction* instruction);
int8 getArgument(Instruction* instruction);
