private
setUp
	program := UziProgramNode.
	varDec := UziVariableDeclarationNode.
	proc := UziProcedureNode.
	assignment := UziAssignmentNode.
	var := UziVariableNode.
	prim := UziPrimitiveCallNode.
	number := UziNumberLiteralNode.
	block := UziBlockNode.
	conditional := UziConditionalNode.
	task := UziTaskNode.
	until := UziUntilNode.
	doUntil := UziDoUntilNode.
	start := UziScriptStartNode.
	stop := UziScriptStopNode.
	repeat := UziRepeatNode.
	pause := UziScriptPauseNode.
	resume := UziScriptResumeNode.
	forever := UziForeverNode.
	for := UziForNode.
	tickingRate := UziTickingRateNode