private
corePrimitives
	^ {			
	prim name: #turnOn.
	prim name: #turnOff.
	prim name: #read.
	prim name: #write.
	prim name: #toggle.
	prim name: #servoDegrees.
	prim name: #servoWrite.
	prim alias: #+ name: #add.
	prim alias: #- name: #subtract.
	prim alias: #* name: #multiply.
	prim alias: #/ name: #divide.
	prim name: #sin.
	prim name: #cos.
	prim name: #tan.
	prim alias: #== name: #equals.
	prim alias: #!= name: #notEquals.
	prim alias: #> name: #greaterThan.
	prim alias: #>= name: #greaterThanOrEquals.
	prim alias: #< name: #lessThan.
	prim alias: #<= name: #lessThanOrEquals.
	prim alias: #! name: #negate.
	prim name: #delayMs.
	prim alias: #& name: #bitwiseAnd.
	prim alias: #| name: #bitwiseOr.
	prim name: #millis.
	prim name: #coroutine.
	prim name: #serialWrite.
	prim name: #round.
	prim name: #ceil.
	prim name: #floor.
	prim name: #sqrt.
	prim name: #abs.
	prim name: #ln.
	prim name: #log10.
	prim name: #exp.
	prim name: #pow10.
	prim name: #asin.
	prim name: #acos.
	prim name: #atan.
	prim alias: #** name: #power.
	prim name: #isOn.
	prim name: #isOff.
	prim alias: #% name: #mod.
	prim name: #constrain.
	prim name: #randomInt.
	prim name: #random.
	prim name: #isEven.
	prim name: #isOdd.
	prim name: #isPrime.
	prim name: #isWhole.
	prim name: #isPositive.
	prim name: #isNegative.
	prim name: #isDivisibleBy.
	prim name: #seconds.
	prim name: #isCloseTo.
	prim name: #delayS.
	prim name: #delayM.
	prim name: #minutes.
	prim name: #sonarDistCm.
	}